### ISSUE TITLE
Help with Install

### ISSUE THREAD

**Issue by psegovias** [jonathanchrisp/bwapi#176]
Hi, any guide to install?

Regards!

**Comment by jonathanchrisp** [comment]
Hi @psegovias, depending on whether your machine is properly configured you should be able to just do: `gem install bwapi` from the terminal/console.

**Comment by psegovias** [comment]
This is a custom dashboard to brandwatch?

**Comment by jonathanchrisp** [comment]
No this is our Ruby API wrapper, you can find out more information here: https://github.com/jonathanchrisp/bwapi/blob/master/README.md

**Comment by psegovias** [comment]
Oh i see, sorry, do u know a custom dashboard to brandwatch?

**Comment by jonathanchrisp** [comment]
Apologies I don't, however Brandwatch does sell a product called [Vizia](http://www.brandwatch.com/brandwatch-vizia/). It might suit your needs.

**Comment by psegovias** [comment]
yes, i know, but i need my own display attach to BW API.

Thanks!
